name: ted_test
description: A starting point for Dart libraries or applications.
version: 0.0.0
repository: https://github.com/andreilg/ted_test

environment:
  sdk: '>=2.17.6 <3.0.0'

#dependencies:

dev_dependencies:
  glados: ^1.1.4
  test: ^1.21.4
  very_good_analysis: ^3.0.1
