name: Continuous Deployment

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'pubspec.yaml'
      - 'CHANGELOG.md'

jobs:
  first:
    name: Continuous Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          version-file: 'pubspec.yaml'



