name: Conventional Changelog Action
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'pubspec.yaml'
      - 'CHANGELOG.md'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.ACTION_TOKEN }}
          version-file: 'pubspec.yaml'
