name: Continuous Deployment

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'pubspec.yaml'
      - 'CHANGELOG.md'

jobs:
  first:
    name: Continuous Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTION_TOKEN }}
          persist-credentials: false
        
      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          version-file: 'pubspec.yaml'



