name: Continuous Deployment

on:
  push:
    branches: [ main ]
    paths-ignore:
      - pubspec.yaml
      - CHANGELOG.md

jobs:
  first:
    name: Continuous Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Create changelog
        uses: TriPSs/conventional-changelog-action@v3.14.1 
        with:
          github-token: ${{ secrets.ACTION_TOKEN }}
          version-file: pubspec.yaml
          fallback-version: 0.0.1
