name: Conventional Changelog Action
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'pubspec.yaml'
      - 'CHANGELOG.md'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
