name: Conventional Changelog Action
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'pubspec.yaml'
      - 'CHANGELOG.md'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
        with:
          github-token: ${{ secrets.github_token }}
        
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
