name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  first:
    name: Continuous Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2
    
      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.14.1 
        with:
          github-token: ${{ secrets.ACTION_TOKEN }}
          version-file: pubspec.yaml
          fallback-version: 0.0.1

      - name: Create release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
