name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  first:
    name: Continuous Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Create release and changelog
        uses: google-github-actions/release-please-action@v3.1.2
        with:
          release-type: dart
          package-name: ted_test
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
