name: Semantic Pull Request

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
      with:
        ignoreLabels: |
          bot
          ignore-semantic-pull-request
        disallowScopes: |
          release
        ignoreLabels: |
          bot
          ignore-semantic-pull-request
